my_blog/about/urls.py
from django.conf.urls import url

from about import views

urlpatterns=[
    url(r'^$', views.get_about, name='about')

]

my_blog/article/urls.py
from django.conf.urls import url

from article import views

urlpatterns=[
    url(r'^$', views.get_article, name='article'),
    url(r'^all/', views.show_all_article),
    url(r'detail/(?P<id>[0-9]+)/$', views.show_article_by_id),
    url(r'detail/(?P<id>[0-9]+)/comment/$', views.save_user_comment),
    url(r'tags/$', views.show_all_tag),
    url(r'tag/(?P<tag_id>[0-9]+)/', views.get_article_by_tag, name='get_article_by_tag'),


]

my_blog/home/urls.py
from django.conf.urls import url

from home import views

urlpatterns=[
    url(r'^$', views.get_home, name='home')

]

my_blog/my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.get_home),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^resource/', include('resource.urls', namespace='resource')),
    url(r'^timeline/', include('timeline.urls', namespace='timeline')),
    url(r'background/',include('my_background.urls', namespace='my_background')),
]

my_blog/resource/urls.py
from django.conf.urls import url

from resource import views

urlpatterns=[
    url(r'^$', views.get_resource, name='resource')

]

my_blog/timeline/urls.py
from django.conf.urls import url

from timeline import views

urlpatterns=[
    url(r'^$', views.get_timeline, name='timeline')

]

my_blog/article/models.py
from datetime import datetime
from django.db import models


class ArticleTag(models.Model):
    """
    文章分类标签
    """
    tag_name = models.CharField(max_length=32, null=False, unique=True)  # 文章标签
    create_time = models.DateTimeField(auto_now=datetime.now())  # 创建时间
    is_delete = models.BooleanField(default=0)  # 是否禁用

    class Meta:
        db_table = 'tb_article_tag'

    def to_dict(self):
        return {
            'tag_name':self.tag_name,
            'tag_id':self.id
        }



class MyArticle(models.Model):
    """
    文章
    """
    title = models.CharField(max_length=64, null=False)  # 标题
    author = models.CharField(max_length=32, null=False)  # 作者
    abstract = models.CharField(max_length=128, null=False)  # 摘要

    article = models.TextField(null=False)  # 文章
    create_time = models.DateTimeField(auto_now_add=True, null=False)  # 创建时间
    update_time = models.DateTimeField(auto_now=datetime.now(), null=False)  # 更新时间
    count_of_read = models.IntegerField(default=0, null=True)  # 阅读数
    count_of_comment = models.IntegerField(default=0, null=True)  # 评论数
    recommend = models.BooleanField(default=0)  # 推荐
    auditing = models.BooleanField(default=0)  # 审核
    is_show = models.BooleanField(default=0)  # 展示
    tag = models.ForeignKey(ArticleTag)  # 标签

    class Meta:
        db_table = 'tb_article'

    def main_to_dict(self):
        return {
            'id':self.id,
            'title':self.title,
            'author': self.author,
            'abstract':self.abstract,
            'tag': self.tag.tag_name,
            'create_time': self.create_time,
            'count_of_read': self.count_of_read,
            'count_of_comment':self.count_of_comment,
            'recommend':self.recommend,
            'auditing':self.auditing,
            'is_show':self.is_show
        }

    def all_to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'author': self.author,
            'abstract': self.abstract,
            'tag': self.tag.tag_name,
            'article':self.article,
            'create_time': self.create_time,
            'update_time':self.update_time,
            'count_of_read': self.count_of_read,
            'count_of_comment': self.count_of_comment
        }


class ReaderComment(models.Model):
    """
    评论
    """
    reader_name = models.CharField(max_length=32, null=False)  # 评论用户名
    comment_time = models.DateTimeField(auto_now=datetime.now(), null=False)  # 评论时间
    comment = models.TextField(null=False)  # 评论
    head_img = models.CharField(max_length=128) # 评论者头像
    article_id = models.ForeignKey(MyArticle, on_delete=models.PROTECT)

    class Meta:
        db_table = 'tb_reader_comment'

my_blog/article/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, reverse

from article.models import MyArticle, ReaderComment, ArticleTag
# Create your views here.
def get_article(request):
    """
    返回article页面
    """
    if request.method == 'GET':
        # tag_id = request.GET.get('tag')
        # if tag_id:
        #     return HttpResponseRedirect(reverse('article:get_article_by_tag', args=(tag_id,)))
        return render(request, 'article.html')


def show_all_article(request):
    """
    获取所有文章的接口
    :return: 返回查询结果Json
    """
    if request.method == 'GET':
        articles = MyArticle.objects.all()
        article_list = []
        for article in articles:
            if article.is_show == 1:
                article_info = article.main_to_dict()
                article_list.append(article_info)
        data = {'code':200, 'article_list':article_list}
        return JsonResponse(data=data)


def show_article_by_id(request, id):
    """
    通过文章id获取文章
    :param id: 文章id
    :return: detail页面和文章data
    """
    if request.method == 'GET':
        article_res = MyArticle.objects.filter(id=id).first()
        # data = {'article':article_res.all_to_dict()}
        article_res.count_of_read += 1
        article_res.save()
        data = {'article': article_res}
        return render(request, 'detail.html', data)


def save_user_comment(request, id):
    """
    文章评论
    :param id: 文章id
    :return: Json，包含评论时间
    """
    if request.method == 'POST':
        comment_info = request.POST
        reader_name = comment_info.get('reader_name')
        comment = comment_info.get('comment')
        head_img = comment_info.get('head_img')
        article_id = int(id)
        article = MyArticle.objects.filter(id=article_id).first()
        article.count_of_comment += 1
        reader_comment = ReaderComment.objects.create(reader_name=reader_name,
                                      comment=comment,
                                      head_img=head_img,
                                      article_id_id=article_id)
        article.save()
        data = {'code':200,'comment_time':reader_comment.comment_time}
        return JsonResponse(data)


def show_all_tag(request):
    """
    分类标签请求接口
    :return: json
    """
    if request.method == 'GET':
        tags = ArticleTag.objects.all()
        tag_list = []
        for tag in tags:
            if not tag.is_delete:
                tag_list.append(tag.to_dict())
        data = {'code': 200,'tags': tag_list}
        return JsonResponse(data)


def get_article_by_tag(request, tag_id):
    """
    分类查询文章接口
    :param tag_id: 分类标签id
    :return: json，如果有结果，返回查询结果
    """
    tag_article = MyArticle.objects.filter(tag_id=tag_id)
    if tag_article:
        article_list = []
        for article in tag_article:
            if article.is_show == 1:
                article_info = article.main_to_dict()
                article_list.append(article_info)
        data = {'code': 200, 'article_list': article_list}
    else:
        data= {'code': 0}
    return JsonResponse(data)

my_blog/home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

my_blog/templates/article.html
<!--
    
 @Name：不落阁整站模板源码
 @Author：Absolutely
 @Site：http://www.lyblogs.cn

 -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
    不落阁 - 文章专栏
{% endblock %}

{% block extCSS %}
    {{ block.super }}
    <!--本页样式表-->
    <link href="{% static 'css/article.css' %}" rel="stylesheet" />
{% endblock %}
<!DOCTYPE html>


{% block content %}
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="{% url 'home:home' %}" title="网站首页">网站首页</a>
                <a><cite>文章专栏</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main-left">
{#                    <div class="shadow" style="text-align:center;font-size:16px;padding:40px 15px;background:#fff;margin-bottom:15px;">#}
{#                        未搜索到与【<span style="color: #FF5722;">keywords</span>】有关的文章，随便看看吧！#}
{#                    </div>#}
                </div>
                {% verbatim %}
                <script type="text/html" id="show_article">
                {{ if articles }}
                {{ each articles as article }}
                <div class="article shadow">
                        <div class="article-left">
                            <img src="/static/images/cover/201703181909057125.jpg" alt="{{ article.title }}" />
                        </div>
                        <div class="article-right">
                            <div class="article-title">
                                <a href="/article/detail/{{ article.id }}/">{{ article.title }}</a>
                            </div>
                            <div class="article-abstract">
                                {{ article.abstract }}
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="article-footer">
                            <span><i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{ article.create_time }}</span>
                            <span class="article-author"><i class="fa fa-user"></i>&nbsp;&nbsp;{{ article.author }}</span>
                            <span><i class="fa fa-tag"></i>&nbsp;&nbsp;<a href="#">{{ article.tag }}</a></span>
                            <span class="article-viewinfo"><i class="fa fa-eye"></i>&nbsp;{{ article.count_of_read }}</span>
                            <span class="article-viewinfo"><i class="fa fa-commenting"></i>&nbsp;{{ article.count_of_comment }}</span>
                        </div>
                    </div>
                {{ /each }}
                {{ else }}
                <div class="shadow" style="text-align:center;font-size:16px;padding:40px 15px;background:#fff;margin-bottom:15px;">
                        该分类还没有文章
                    </div>
                {{ /if }}
                </script>
                {% endverbatim %}
                <div class="blog-main-right">
                    <div class="blog-search">
                        <form class="layui-form" action="">
                            <div class="layui-form-item">
                                <div class="search-keywords  shadow">
                                    <input type="text" name="keywords" lay-verify="required" placeholder="输入关键词搜索" autocomplete="off" class="layui-input">
                                </div>
                                <div class="search-submit  shadow">
                                    <a class="search-btn" lay-submit="formSearch" lay-filter="formSearch"><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="article-category shadow">
                        <div class="article-category-title">分类导航</div>


                    </div>
                    {% verbatim %}
                    <script type="text/html" id="show_tags">
                        {{ each tags as tag }}
                        <a href="javascript:void(0)" onclick="get_article_by_tag({{ tag.tag_id }})">{{ tag.tag_name }}</a>
                        {{ /each }}
                        <div class="clear"></div>
                    </script>
                    {% endverbatim %}

                    <div class="blog-module shadow">
                        <div class="blog-module-title">作者推荐</div>
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">Web安全之跨站请求伪造CSRF</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC 防范跨站请求伪造（CSRF）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">C#基础知识回顾-扩展方法</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（一）（HTML篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（二）（CSS篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（三）（JS篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">写了个Win10风格快捷菜单！</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC自定义错误页</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC制作404跳转（非302和200）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">基于laypage的layui扩展模块（pagesize.js）！</a></li>
                        </ul>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">随便看看</div>
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（一）（HTML篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC制作404跳转（非302和200）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC 防范跨站请求伪造（CSRF）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（三）（JS篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">基于laypage的layui扩展模块（pagesize.js）！</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（二）（CSS篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">写了个Win10风格快捷菜单！</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">常用正则表达式</a></li>
                        </ul>
                    </div>
                    <!--右边悬浮 平板或手机设备显示-->
                    <div class="category-toggle"><i class="fa fa-chevron-left"></i></div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extJS %}
    {{ block.super }}
    <script type="text/javascript">
        layui.use(['jquery'], function () {
            var $ = layui.jquery;
            $('.fa-file-text').parent().parent().attr('class', 'layui-nav-item layui-this');
            {#如果url中传递了参数，则请求分类文章，否则请求全部文章#}
            if (location.search){
                var url = '/article/tag/'+location.search.split('=')[1]
                $.get(url,function (data) {
                    if (data.code == 200){
                        var article_html = template('show_article',{articles:data.article_list})
                        $('.blog-main-left').html(article_html)
                    }else if(data.code == 0){
                        var article_html = template('show_article',{articles:data.article_list})
                        $('.blog-main-left').html(article_html)
                    }
                })
            }else {

                $.get(url='/article/all/', function (data) {
                    if (data.code == 200){
                        var article_html = template('show_article',{articles:data.article_list})
                        $('.blog-main-left').html(article_html)
                    }
                });
            }
            {#加载分类#}
            $.get(url='/article/tags/',function (data) {
                if (data.code == 200){
                    var tag_html = template('show_tags', {tags:data.tags})
                    $('.article-category').append(tag_html)
                }
            });
        });

        {#分类点击，动态加载分类查询结果#}
        function get_article_by_tag(id) {
            {#发送请求的url#}
            var get_url = '/article/tag/'+id + '/';
            {#地址栏展示的url,只更新不跳转页面#}
            var url = '/article/?tag='+id;
            history.replaceState('更新当前url',null,url)
            layui.use(['jquery'], function () {
                var $ = layui.jquery;
                $.get(get_url,function (data) {
                    if (data.code == 200){
                        var article_html = template('show_article',{articles:data.article_list})
                        $('.blog-main-left').html(article_html)
                    }else if(data.code == 0){
                        var article_html = template('show_article',{articles:data.article_list})
                        $('.blog-main-left').html(article_html)
                    }
                })
            })
        }


    </script>
{% endblock %}

my_blog/templates/base.html
{% load static %}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; Charset=gb2312">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
{% block extCSS %}
    <link rel="shortcut icon" href="{% static 'images/Logo_40.png' %}" type="image/x-icon">
    <!--Layui-->
    <link href="{% static 'plug/layui/css/layui.css' %}" rel="stylesheet" />
    <!--font-awesome-->
    <link href="{% static 'plug/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!--全局样式表-->
    <link href="{% static 'css/global.css' %}" rel="stylesheet" />
{% endblock %}
</head>
<body>
{% block nav %}
    <nav class="blog-nav layui-header">
        <div class="blog-container">
            <!-- QQ互联登陆 -->
            <a href="javascript:;" class="blog-user">
                <i class="fa fa-qq"></i>
            </a>
            <a href="javascript:;" class="blog-user layui-hide">
                <img src="{% static 'images/Absolutely.jpg' %}" alt="Absolutely" title="Absolutely" />
            </a>
            <!-- 不落阁 -->
            <a class="blog-logo" href="{% url 'home:home' %}">不落阁</a>
            <!-- 导航菜单 -->
            <ul class="layui-nav" lay-filter="nav">
                <li class="layui-nav-item">
                    <a href="{% url 'home:home' %}"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'article:article' %}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'resource:resource' %}"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'timeline:timeline' %}"><i class="fa fa-hourglass-half fa-fw"></i>&nbsp;点点滴滴</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'about:about' %}"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
                </li>
            </ul>
            <!-- 手机和平板的导航开关 -->
            <a class="blog-navicon" href="javascript:;">
                <i class="fa fa-navicon"></i>
            </a>
        </div>
    </nav>
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
    <!-- 底部 -->
    <footer class="blog-footer">
        <p><span>Copyright</span><span>&copy;</span><span>2017</span><a href="http://www.lyblogs.cn">不落阁</a><span>Design By LY</span></p>
        <p><a href="http://www.miibeian.gov.cn/" target="_blank">蜀ICP备16029915号-1</a></p>
    </footer>
    <!--侧边导航-->
    <ul class="layui-nav layui-nav-tree layui-nav-side blog-nav-left layui-hide" lay-filter="nav">
        <li class="layui-nav-item">
            <a href="{% url 'home:home' %}"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'article:article' %}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'resource:resource' %}"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'timeline:timeline' %}"><i class="fa fa-road fa-fw"></i>&nbsp;点点滴滴</a>
        </li>
        <li class="layui-nav-item">
            <a href="{% url 'about:about' %}"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
        </li>
    </ul>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>

{% endblock %}

{% block extJS %}
    <!-- layui.js -->
    <script src="{% static 'plug/layui/layui.js' %}"></script>
    <!-- 全局脚本 -->
    <script src="{% static 'js/global.js' %}"></script>
    <script src="{% static 'js/template.js' %}"></script>
{% endblock %}

</body>
</html>

my_blog/templates/detail.html
<!--
    
 @Name：不落阁整站模板源码
 @Author：Absolutely
 @Site：http://www.lyblogs.cn

 -->
{% extends 'base.html' %}
{% load static %}
{% block title %}
不落阁 - 文章专栏 - 基于layui的laypage扩展模块！
{% endblock %}
{% block extCSS %}
    {{ block.super }}
    <!-- 比较好用的代码着色插件 -->
    <link href="{% static 'css/prettify.css' %}" rel="stylesheet" />
    <!-- 本页样式表 -->
    <link href="{% static 'css/detail.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <!-- 主体（一般只改变这里的内容） -->

    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="{% url 'home:home' %}" title="网站首页">网站首页</a>
                <a href="{% url 'article:article' %}" title="文章专栏">文章专栏</a>
                <a><cite>{{ article.title }}</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main-left">
                    <!-- 文章内容（使用Kingeditor富文本编辑器发表的） -->
                    <div class="article-detail shadow">
                        <div class="article-detail-title">
                            {{ article.title }}
                        </div>
                        <div class="article-detail-info">
                            <span>编辑时间：{{ article.update_time }}</span>
                            <span>作者：{{ article.author }}</span>
                            <span>浏览量：{{ article.count_of_read }}</span>
                        </div>
                        <div class="article-detail-content">
                            {{ article.article | safe }}
                        </div>
                    </div>
                    <!-- 评论区域 -->
                    <div class="blog-module shadow" style="box-shadow: 0 1px 8px #a6a6a6;">
                        <fieldset class="layui-elem-field layui-field-title" style="margin-bottom:0">
                            <legend>来说两句吧</legend>
                            <div class="layui-field-box">
                                <form class="layui-form blog-editor" action="">
                                    {% csrf_token %}
                                    <div class="layui-form-item">
                                        <textarea name="editorContent" lay-verify="content" id="remarkEditor" placeholder="请输入内容" class="layui-textarea layui-hide"></textarea>
                                    </div>
                                    <div class="layui-form-item">
                                        <button class="layui-btn" lay-submit="formRemark" lay-filter="formRemark">提交评论</button>
                                    </div>
                                </form>
                            </div>
                        </fieldset>
                        <div class="blog-module-title">最新评论</div>
                        <ul class="blog-comment">
                            {% for comment in article.readercomment_set.all %}
                            <li>
                                <div class="comment-parent">
                                    <img src="{{ comment.head_img }}" alt="absolutely" />
                                    <div class="info">
                                        <span class="username">{{ comment.reader_name }}</span>
                                        <span class="time">{{ comment.comment_time }}</span>
                                    </div>
                                    <div class="content">
                                        {{ comment.comment }}
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="blog-main-right">
                    <!--右边悬浮 平板或手机设备显示-->
                    <div class="category-toggle"><i class="fa fa-chevron-left"></i></div><!--这个div位置不能改，否则需要添加一个div来代替它或者修改样式表-->
                    <div class="article-category shadow">
                        <div class="article-category-title">分类导航</div>
                        <!-- 点击分类后的页面和artile.html页面一样，只是数据是某一类别的 -->
                    </div>
                    {% verbatim %}
                    <script type="text/html" id="show_tags">
                        {{ each tags as tag }}
                        <a href="/article/?tag={{ tag.tag_id }}">{{ tag.tag_name }}</a>
                        {{ /each }}
                        <div class="clear"></div>
                    </script>
                    {% endverbatim %}
                    <div class="blog-module shadow">
                        <div class="blog-module-title">相似文章</div>
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">基于laypage的layui扩展模块（pagesize.js）！</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">基于laypage的layui扩展模块（pagesize.js）！</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">基于laypage的layui扩展模块（pagesize.js）！</a></li>
                        </ul>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">随便看看</div>
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（一）（HTML篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC制作404跳转（非302和200）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">ASP.NET MVC 防范跨站请求伪造（CSRF）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（三）（JS篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">基于laypage的layui扩展模块（pagesize.js）！</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">一步步制作时光轴（二）（CSS篇）</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">写了个Win10风格快捷菜单！</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>

{% endblock %}

{% block extJS %}
    {{ block.super }}
    <!-- 比较好用的代码着色插件 -->
    <script src="{% static 'js/prettify.js' %}"></script>
    <!-- 本页脚本 -->
    <script src="{% static 'js/detail.js' %}"></script>
    <script type="text/javascript">
        layui.use(['jquery'], function () {
            var $ = layui.jquery;
            $('.fa-file-text').parent().parent().attr('class', 'layui-nav-item layui-this');
            $.get(url='/article/tags/',function (data) {
                if (data.code == 200){
                    var tag_html = template('show_tags', {tags:data.tags})
                    $('.article-category').append(tag_html)
                }
            });
        });

        {#function get_article_by_tag(id) {#}
        {#    var url = '/article/?tag=' + id#}
        {#    history.replaceState({'xxx':'xxx'},null,url)#}
        {#    layui.use(['jquery'], function () {#}
        {#        var $ = layui.jquery;#}
        {#        $.get(url,function (data) {#}
        {#            if (data.code == 200){#}
        {#                var article_html = template('show_article',{articles:data.article_list})#}
        {#                $('.blog-main-left').html(article_html)#}
        {#            }else if(data.code == 0){#}
        {#                var article_html = template('show_article',{articles:data.article_list})#}
        {#                $('.blog-main-left').html(article_html)#}
        {#            }#}
        {#        })#}
        {#    })#}
        {#}#}

    </script>
{% endblock %}